version: "3.9"
services:
  redis:
    container_name: redis
    hostname: redis
    image: redis:7-alpine
    restart: always
    networks:
      - wordpress

  mariadb:
    container_name: mariadb
    hostname: mariadb
    image: mariadb:11-jammy
    restart: always
    volumes:
      - ./data/db:/var/lib/mysql
    env_file:
      - ./conf/db/db.env
    networks:
      - wordpress

  wordpress:
    container_name: wordpress
    hostname: wordpress
    build:
      context: ./docker/wordpress
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mariadb
      - redis
    volumes:
      - ./data/html:/var/www/html
      - ./conf/wordpress/php.ini:/usr/local/etc/php/conf.d/php_optional.ini
    env_file:
      - ./conf/wordpress/wordpress.env
    environment:
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_REDIS_HOST', 'redis');
        define('WP_REDIS_PORT', '6379');
        define('WP_MEMORY_LIMIT', '768M');
        define('WP_MAX_MEMORY_LIMIT', '1024M');
        define('WP_DEBUG', false);
        define('WP_DEBUG_LOG', false);
        define('WP_DEBUG_DISPLAY', false);
    networks:
      - wordpress

  caddy:
    container_name: caddy
    hostname: caddy
    build:
      context: ./docker/caddy
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./conf/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./data/html:/var/www/html
      - ./data/caddy/data:/data
      - ./data/caddy/config:/config
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    env_file:
      - ./conf/caddy/caddy.env
    networks:
      - wordpress

networks:
  wordpress:
    driver: bridge
    name: wordpress
